version: "3.8"

name: wlss-local-dev

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    env_file:
      - .env
    ports:
        - "9000:9000"
        - "9001:9001"
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

volumes:
  postgres:
  minio:
