"""change avatar to avatar_id

Revision ID: 55f1606e7086
Revises: d7454b0101c0
Create Date: 2023-11-19 21:20:01.224200+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55f1606e7086"
down_revision = "d7454b0101c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("avatar_id", sa.UUID(), nullable=True))
    op.create_unique_constraint("profile_avatar_id_key", "profile", ["avatar_id"])

    op.drop_constraint("profile_avatar_key", "profile", type_="unique")
    op.drop_column("profile", "avatar")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("avatar", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint("profile_avatar_key", "profile", ["avatar"])

    op.drop_constraint("profile_avatar_id_key", "profile", type_="unique")
    op.drop_column("profile", "avatar_id")
    # ### end Alembic commands ###
