"""remove poc models

Revision ID: 8f2f6221d1de
Revises: a6c565d21b95
Create Date: 2023-06-15 11:58:39.592665+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f2f6221d1de"
down_revision = "a6c565d21b95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("bucket", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="entity_pkey"),
    )
    # ### end Alembic commands ###
