"""add entity table

Revision ID: 746039e79eb3
Revises:
Create Date: 2023-05-08 23:06:50.807486+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "746039e79eb3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("entity", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity")
    # ### end Alembic commands ###
