"""add bucket and key to entity

Revision ID: a6c565d21b95
Revises: 746039e79eb3
Create Date: 2023-05-13 00:36:11.388267+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6c565d21b95"
down_revision = "746039e79eb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("bucket", sa.String(), nullable=False))
    op.add_column("entity", sa.Column("key", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "key")
    op.drop_column("entity", "bucket")
    # ### end Alembic commands ###
