"""add instance and floating_ip tables

Revision ID: 5c530dfcd1ac
Revises: 8f2f6221d1de
Create Date: 2023-09-23 15:01:31.071962+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c530dfcd1ac"
down_revision = "8f2f6221d1de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floating_ip",
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("ip"),
    )
    op.create_table(
        "instance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instance")
    op.drop_table("floating_ip")
    # ### end Alembic commands ###
