"""create file table

Revision ID: 1b645cd5f92c
Revises: 21c255263879
Create Date: 2024-02-18 10:44:03.839896+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b645cd5f92c"
down_revision = "21c255263879"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "extension",
            sa.Enum("GIF", "JFIF", "JIF", "JPE", "JPEG", "JPG", "PNG", "WEBP", name="extension_enum"),
            nullable=False,
        ),
        sa.Column(
            "mime_type",
            sa.Enum("IMAGE_GIF", "IMAGE_JPEG", "IMAGE_PNG", "IMAGE_WEBP", name="mime_type_enum"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file")
    sa.Enum(name="extension_enum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="mime_type_enum").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
