"""create wish table

Revision ID: 7d85d9d7e37d
Revises: bbcbf8bbffd1
Create Date: 2024-02-20 20:26:34.431744+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d85d9d7e37d"
down_revision = "bbcbf8bbffd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wish",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("avatar_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=10000), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["avatar_id"],
            ["file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("avatar_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wish")
    # ### end Alembic commands ###
