"""add unique together for account_id and wish_id

Revision ID: 69d6fbe5d8cd
Revises: 5b979f00b2de
Create Date: 2024-02-26 19:01:08.858249+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69d6fbe5d8cd"
down_revision = "5b979f00b2de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("account_id__wish_id__unique_together", "wish_booking", ["account_id", "wish_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("account_id__wish_id__unique_together", "wish_booking", type_="unique")
    # ### end Alembic commands ###
