"""add length constraints to existing string columns

Revision ID: a8b78318faef
Revises: 55f1606e7086
Create Date: 2024-01-23 14:18:20.106426+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8b78318faef"
down_revision = "55f1606e7086"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "email", type_=sa.String(200))
    op.alter_column("account", "login", type_=sa.String(50))

    op.alter_column("profile", "description", type_=sa.String(1000))
    op.alter_column("profile", "name", type_=sa.String(100))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "email", type_=sa.String)
    op.alter_column("account", "login", type_=sa.String)

    op.alter_column("profile", "description", type_=sa.String)
    op.alter_column("profile", "name", type_=sa.String)
    # ### end Alembic commands ###
