version: "3.8"

services:
  app-build: &app-build
    build:
      context: ../..  # path from the corrent file to the project root dir
      dockerfile: envs/ci/Dockerfile  # path from the project root dir to the Dockerfile
      cache_from:
        - type=local,src=${BUILDX_CACHE_SRC}
      cache_to:
        - type=local,dest=${BUILDX_CACHE_DEST}

  mypy:
    <<: *app-build
    entrypoint: mypy

  ruff:
    <<: *app-build
    entrypoint: ruff check src tests

  flake8:
    <<: *app-build
    entrypoint: flake8

  pylint:
    <<: *app-build
    entrypoint: pylint src tests

  pytest:
    <<: *app-build
    entrypoint: pytest --cov=src
