name: Lint
run-name: Lint commit "${{ github.sha }}"

on: push
jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: ./.github/actions/docker/use-buildx-cache

      - name: Build mypy
        run: docker compose --file envs/ci/docker-compose.yml build mypy

      - name: Run mypy
        run: docker compose --file envs/ci/docker-compose.yml run mypy

      - name: Update buildx cache
        uses: ./.github/actions/docker/update-buildx-cache

  ruff:
    name: Ruff
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: ./.github/actions/docker/use-buildx-cache

      - name: Build ruff
        run: docker compose --file envs/ci/docker-compose.yml build ruff

      - name: Run ruff
        run: docker compose --file envs/ci/docker-compose.yml run ruff

      - name: Update buildx cache
        uses: ./.github/actions/docker/update-buildx-cache

  flake8:
    name: Flake8
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: ./.github/actions/docker/use-buildx-cache

      - name: Build flake8
        run: docker compose --file envs/ci/docker-compose.yml build flake8

      - name: Run flake8
        run: docker compose --file envs/ci/docker-compose.yml run flake8

      - name: Update buildx cache
        uses: ./.github/actions/docker/update-buildx-cache

  pylint:
    name: Pylint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: ./.github/actions/docker/use-buildx-cache

      - name: Build pylint
        run: docker compose --file envs/ci/docker-compose.yml build pylint

      - name: Run pylint
        run: docker compose --file envs/ci/docker-compose.yml run pylint

      - name: Update buildx cache
        uses: ./.github/actions/docker/update-buildx-cache
