name: Test
run-name: Test commit "${{ github.sha }}"

on: push
jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: ./.github/actions/docker/use-buildx-cache

      - name: Cache pytest
        uses: actions/cache@v3
        with:
          path: ./.pytest_cache
          key: pytest-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            pytest-${{ runner.os }}-${{ github.ref_name }}
            pytest-${{ runner.os }}-${{ github.event.repository.default_branch }}

      - name: Build pytest
        run: docker compose --file envs/ci/lint/docker-compose.yml build pytest

      - name: Run pytest
        run: docker compose --file envs/ci/lint/docker-compose.yml run pytest

      - name: Update buildx cache
        uses: ./.github/actions/docker/update-buildx-cache
